version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge